### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by lucasmari** [oracle/oci-grafana-logs#107]
Hey, I've noticed a small error in [kubernetes](https://github.com/oracle/oci-grafana-logs/blob/main/docs/kubernetes.md) and [linuxoci](https://github.com/oracle/oci-grafana-logs/blob/main/docs/linuxoci.md) files.

They both have the first policy statement with two verbs (read), lines 28 and 24 respectively.

**Comment by mamorett** [comment]
Thanks for the head up :) We will update the docs

**Comment by mamorett** [comment]
done. Thanks again to have noticed it. :)

**Comment by lucasmari** [comment]
No problem ;)
