### ISSUE TITLE
OCI Logging plugin stopped working with Grafana 8

### ISSUE THREAD

**Issue by tonychoe** [oracle/oci-grafana-logs#11]
It's the same issue with the metrics plugin. Can you please fix it?

**Comment by EdsonBittencourt** [comment]
Not working here too.

**Comment by RalfMa** [comment]
Same here :(

**Comment by tonychoe** [comment]
This is fixed with the v2 plugin. https://grafana.com/grafana/plugins/oci-logs-datasource/
