### ISSUE TITLE
Not working yet in ARM architecture

### ISSUE THREAD

**Issue by EdsonBittencourt** [oracle/oci-grafana-logs#14]
Hello,

Trying to configure it in ARM server inside OCI and it isn't working. Metric datasource doesn't working neither.

```
t=2022-01-06T17:18:54+0000 lvl=eror msg="Could not start plugin" logger=plugin.manager pluginId=oci-logs-datasource err="fork/exec /var/lib/grafana/plugins/oci-logs-datasource/oci-plugin_linux_arm64: no such file or directory"
t=2022-01-06T17:18:54+0000 lvl=eror msg="Could not start plugin" logger=plugin.manager pluginId=oci-metrics-datasource err="fork/exec /var/lib/grafana/plugins/oci-metrics-datasource/oci-plugin_linux_arm64: no such file or directory"
```

Thanks.

**Comment by huskerdhf** [comment]
Hi @EdsonBittencourt,

Linux and Mac ARM support has been added as part of the 2.0.2 release of the logging plugin. Please try the most release of the plugin and let us know whether the issue you raised has been addressed.

**Comment by EdsonBittencourt** [comment]
> Hi @EdsonBittencourt,
> 
> Linux and Mac ARM support has been added as part of the 2.0.2 release of the logging plugin. Please try the most recent release of the plugin and let us know whether the issue you raised has been addressed. If no response is received within 30 days, this issue will be closed.

thank you so much, i'll test it asap and let you know the results :D

**Comment by EdsonBittencourt** [comment]
> Hi @EdsonBittencourt,
> 
> Linux and Mac ARM support has been added as part of the 2.0.2 release of the logging plugin. Please try the most recent release of the plugin and let us know whether the issue you raised has been addressed. If no response is received within 30 days, this issue will be closed.

It's working perfectly, thank you so much for your time.
