### ISSUE TITLE
Support multiple OCI tenancies

### ISSUE THREAD

**Issue by tonychoe** [oracle/oci-grafana-logs#18]
Currently, the logs plugin only supports one OCI tenancy per data source. Meaning the OCI users who have multiple tenancies will have to create many data sources and have to constantly switch the data sources. 

To improve the usability, I propose the following:

- Users are able to configure multiple tenancies in a single data source and add a drop down menu of tenancies in the logging UI.

- In the data source, users are able to configure a tenancy display name and OCID together, so the drop down menu can display the display name instead of OCID, which is not human friendly.

Note - this proposal applies to OCI metrics plugin as well.

**Comment by mamorett** [comment]
The current version of the plugin supports multi-tenancy mode. You can upgrade to v4.0.0 of the plugin.
