### ISSUE TITLE
Log result UI needs improvement - word-wrap, remove unnecessary columns, auto-sized column width

### ISSUE THREAD

**Issue by tonychoe** [oracle/oci-grafana-logs#20]
Can you please make the log result UI improved so users can actually see the logs? 

I would suggest the following as the high priority.

(1) Each row must support the word wrap. A long log line is not displayed fully. This is the most serious issue.

(2) Remove the columns of "status", "id". I am not sure what is "status" field and no users would care about the log id.

(3) Remove the "level" column or make it accurate. 

(4) The column width should be auto-sized. Otherwise, users will have to keep resizing it.

<img width="1589" alt="Screen Shot 2022-04-07 at 10 03 55 PM" src="https://user-images.githubusercontent.com/12507518/162368353-b2380c14-d74d-47ac-be5e-34db5ffcf05f.png">

**Comment by huskerdhf** [comment]
Hi @tonychoe,

The latest version of the oci-grafana-logs plugin addresses some of your comments and the rest I believe can be addressed through other Grafana capabilities. Here is an explanation for how each of the items you raised is addressed:

1. Text wrap within cell
    * This is not a characteristic of the presented table that the datasource plugin has control over.
    * This needs to be managed through the Table panel plugin however this is a known issue with the Grafana table panel plugin, see https://github.com/grafana/grafana/issues/25623.
2. Remove status & id columns
    * The status column has been removed since the plugin now only displays the fields that are actually present in the returned log records. Which means the plugin does not try to derive fields such as 'status' that prior versions of the plugin did.
    * The 'id' column still exists since the plugin has been updated to only show the fields present in the returned log records and the 'id' field is one that is included in the log records returned by a logging search query.
    * However the 'id' column (or any other unwanted column) can be hidden using the "Organize fields" transformation.
    * This transformation can be used to control many other aspects of the presented table including hiding columns, re-ordering columns, etc.
3. Remove the level column
    * As referenced in the response to the last item, the plugin has been updated to only show the fields present in the returned log records which means that the level column is no longer shown (unless there is a level field within the returned log records).
4. Column width should be auto-sized
    * Column width auto sizing can be controlled via the Panel Options when editing the data panel configuration. The related configuration settings are available under the Table portion of the panel configuration options.
    * The width of individuals columns can be separately adjusted and the selected width is retained by the Table panel so when the panel is displayed again the same column width is used.

Please try the updated oci-grafana-logs plugin and other Grafana features to determine whether all of your points are addressed. Let us know if you believe that any of the issues are still not addressed. If no response is received within 30 days, this issue will be closed. 

Thanks

**Comment by huskerdhf** [comment]
Since no follow up was received, this issue is being closed. If at a later point in time you are able to test a newer version of the plugin and still have issues related to this or any other topic then please submit a new issue.
