### ISSUE TITLE
Doc page for using the oci-grafana-logs datasource

### ISSUE THREAD

**Issue by vmchiran** [oracle/oci-grafana-logs#9]
Hi,
Looks like the [using.md](https://github.com/oracle/oci-grafana-logs/blob/main/docs/using.md) page reflects the oci-grafana-metrics, instead of oci-grafana-logs.
Please update the content so that it is relevant for the oci-grafana-logs plugin.

Thank you,
Valeria

**Comment by huskerdhf** [comment]
Hi @vmchiran,

The documentation pages for the oci-grafana-logs plugin have been updated to address the OCI logs plugin rather than the OCI metrics plugin as part of the 2.0.2 release. Please try the 2.0.2 release of the plugin to see if the issue you raised has been addressed or not.

**Comment by huskerdhf** [comment]
Since no follow up was received, this issue is being closed. If at a later point in time @vmchiran you are able to review the updated plugin documentation and still have issues related to this or any other topic then please submit a new issue.
